# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab0b12d2120f9ac8dc5e70e79491c25c0661f66a1a0b6e4a5c9ea9b59b6460b7e5772d7605673cfc92d4e5d3eba08e7eb872f9e1c5e23ee967bb357e864f75f3

test:
  secret_key_base: 5b511ce3379d1d93ea6c4c320e9b24f6b06258ef19db954f0913ec36e73ac5e82bb87629959df9104fe1f7904e5dbfbb506dfc1bbf6e9d3f1811a468fd1ed6b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
